import { SquareClient, SquareEnvironment } from 'square';
import { env } from '$env/dynamic/private';
import { HIDE_DETAIL_BAY } from '$lib/features';

/**
 * Square API client — server-only. Never import this in client-side code.
 * Production by default (real catalog drives /store); set
 * SQUARE_ENVIRONMENT=sandbox to fall back to test data.
 */
const isProduction = env.SQUARE_ENVIRONMENT !== 'sandbox';

export const square = new SquareClient({
  token: isProduction
    ? (env.PROD_ACCESS_TOKEN ?? env.SQUARE_ACCESS_TOKEN ?? '')
    : (env.SANDBOX_SECRET ?? env.SQUARE_ACCESS_TOKEN ?? ''),
  environment: isProduction ? SquareEnvironment.Production : SquareEnvironment.Sandbox
});

/** Location ID — production by default, sandbox when explicitly opted in */
export const LOCATION_ID = isProduction
  ? (env.SQUARE_LOCATION_ID ?? '')
  : (env.SQUARE_SANDBOX_LOCATION_ID ?? env.SQUARE_LOCATION_ID ?? '');

/** Square Bookings — production bay team-member IDs.
 *  6 bays: 2 hoist + 3 flat + 1 detail. Each bay is a Square "team member"
 *  that acts as a bookable resource. IDs from scripts/square-bookings.json. */
export type BayType = 'hoist' | 'flat' | 'detail';

export interface BayInfo {
  id: number;
  type: BayType;
  label: string;
  teamMemberId: string;
}

/**
 * Production bay roster — 6 bays (2 hoist, 3 flat, 1 detail) at Wrench Club
 * location `L0D3TRCBPGKY1`. Team member IDs must match `scripts/square-bookings.json`.
 */
const PROD_BAYS: BayInfo[] = [
  { id: 1, type: 'hoist',  label: 'Hoist Bay 1',  teamMemberId: 'TMiRX0Ke9zvPD41I' },
  { id: 2, type: 'hoist',  label: 'Hoist Bay 2',  teamMemberId: 'TMhyzQEsQZVnr-2r' },
  { id: 3, type: 'flat',   label: 'Flat Bay 1',   teamMemberId: 'TMZIBkR6K6ehUYn1' },
  { id: 4, type: 'flat',   label: 'Flat Bay 2',   teamMemberId: 'TMy4YFOq7XXbx3dS' },
  { id: 5, type: 'flat',   label: 'Flat Bay 3',   teamMemberId: 'TMSsGetF72Ze9Qwf' },
  { id: 6, type: 'detail', label: 'Detail Bay 1', teamMemberId: 'TMuuAI_z-nwKx_cZ' }
];

/**
 * Sandbox bay roster — 5 bays (2 hoist, 2 flat, 1 detail). One less flat than
 * prod because Coleman enabled "Bookable online" on 5 sandbox TMs. Covers all
 * three bay types so staging still exercises every code path.
 * Must match `scripts/square-bookings.sandbox.json`.
 */
const SANDBOX_BAYS: BayInfo[] = [
  { id: 1, type: 'hoist',  label: 'Hoist Bay 1',  teamMemberId: 'TMkMik9RL18tkTF7' },
  { id: 2, type: 'hoist',  label: 'Hoist Bay 2',  teamMemberId: 'TMLm78Z2tt7iGsxE' },
  { id: 3, type: 'flat',   label: 'Flat Bay 1',   teamMemberId: 'TM-ELEPsnFgo279C' },
  { id: 4, type: 'flat',   label: 'Flat Bay 2',   teamMemberId: 'TMUSbWTh7cqWRCUM' },
  { id: 5, type: 'detail', label: 'Detail Bay 1', teamMemberId: 'TMYcymhGNoUvtitQ' }
];

/**
 * Active roster, filtered by the HIDE_DETAIL_BAY flag when zoning for
 * "car wash" use is still pending. Catalog/team members stay in Square
 * so we can flip the flag back off without redoing any setup.
 */
const _baseBays = isProduction ? PROD_BAYS : SANDBOX_BAYS;
export const BAYS: BayInfo[] = HIDE_DETAIL_BAY
  ? _baseBays.filter((b) => b.type !== 'detail')
  : _baseBays;

/** Convenience map: bay id → team member id */
export const BAY_TEAM_MEMBERS: Record<number, string> = Object.fromEntries(
  BAYS.map(b => [b.id, b.teamMemberId])
);

/** Bay-type → service variation IDs by hour count (1-8). Linear pricing:
 *    Flat   $25/hr · Detail $30/hr · Hoist $35/hr  */
const PROD_VARIATIONS: Record<BayType, Record<number, string>> = {
  flat: {
    1: 'CWVRBWGVMING4VM24TA2MRLL', 2: 'XMP5HGO6OSNGVGIJKIL7LBF7',
    3: 'B6BMNAPUQZ3J2K5NXVGDDAJA', 4: 'SJHBYAC2TS5LJE6VQVZSFVVL',
    5: 'HSOKWKWPAPZ6LAN4RABXWAZU', 6: 'KV62QRWHTJFE7HIFEO64KK3C',
    7: 'RS5AU4UJYAYJAVUHEXLVLHDJ', 8: 'QKVFQZORNFIRLQYFRDBRW75S'
  },
  detail: {
    1: 'IQV6PZL7LT5HNW6AYFVPG3AX', 2: '5QZAC6WDX3XZYSB4NSEDBBIE',
    3: '6X2BVKAKCV4TV5PXN7435OMS', 4: 'TW52I3FYZVEHBIBDP4KVBDOY',
    5: 'IXP5EMVDL7XIXUIQKDLMCJI2', 6: 'R5ALTP4KQD5PQKABSI5RJUOD',
    7: 'P2ZCUIA7QI6ZK5CLCASF55CW', 8: '7GGH3NLVHB7OVONCVU63AUIF'
  },
  hoist: {
    1: 'NWGQFO7LT5W2MTN53KNKBBZC', 2: '4HOSAOEFXEFPK5A2YVXDTLLJ',
    3: '25GNYIMHH6ITTJMD7MSEXNBY', 4: 'DUL5KIP6VZK5VAFVECEA5MEH',
    5: '636RBFJ4HQSS3RUO4E7YYTIK', 6: 'Z3WDSL7K7QXWIXN3ZNZPYAR2',
    7: '5MIDRMVPXWIYKLRFNFSYPWWN', 8: 'HPUTH7FPE2D2UREETSHO66OB'
  }
};

/** Sandbox variation IDs — regenerated by `square-setup-sandbox-bookings.ts`. */
const SANDBOX_VARIATIONS: Record<BayType, Record<number, string>> = {
  flat: {
    1: 'HYWF2PKX7AWONBQNVCIRFEIK', 2: 'WZD7F53H6WNCSEYIIYEAWNV7',
    3: '5EF5ERWXUNRKSJTOTRG5JVVT', 4: 'WEVC4IGBQDIWT4MOMSIZBUY3',
    5: 'I25SHYNXETB3ZQC73IDH7HI7', 6: 'MNPQFCEZFLOUFFASOBZCHJP2',
    7: 'Z4NFIK6WDSJBYKHC7CG6DFJN', 8: 'QMVXD7NOBMIBZ2IPGIMPADZM'
  },
  detail: {
    1: 'NQLMV5BHPCCH6IC3X2LJQCDA', 2: '56MIKWQTBLJYQKXH7QD2KT3L',
    3: 'LCYWQ7SULELKPQ6YJ2LED6MB', 4: 'IS527PM7GW4FGDS7RCFLEODS',
    5: 'FFDBTCGAS5JFPFGHC7XQ67TP', 6: 'HNJOQZLTS255OYNUIDAYZVYS',
    7: 'AVMYTG7K5JAPYEBI7YQLCFNG', 8: 'DPVYSCCQBVPG3PLSE7ME2KEP'
  },
  hoist: {
    1: 'DAFEAUBINCDTM56MKP3NCHLR', 2: 'S5WYMNK2XNDHVDHOMXSDFUDW',
    3: 'IDGNTQP62VEBZV2TWRN6465M', 4: 'YZYNYTK4LVKENYTOPMJKGVKT',
    5: '23PCQTZJKQTAMLGR3OQIJ2UU', 6: 'CNZXMYRC5UC5WNQOALGAHDAY',
    7: 'PGNCLQGJTYSIE4ZDTACGZJVG', 8: '4JITZABYRTG66BU2JDAQQZZZ'
  }
};

export const BAY_VARIATIONS: Record<BayType, Record<number, string>> =
  isProduction ? PROD_VARIATIONS : SANDBOX_VARIATIONS;

/** Hourly base rate ($/hr) by bay type — pricing is linear. */
export const BAY_HOURLY_RATE: Record<BayType, number> = {
  flat: 25, detail: 30, hoist: 35
};

export const BAY_TYPE_LABEL: Record<BayType, string> = {
  flat: 'Flat Bay', detail: 'Detail Bay', hoist: 'Hoist Bay'
};

/**
 * Add a customer to Square — called at member registration.
 * Stores the returned ID in our local users table.
 */
export async function createSquareCustomer(opts: {
  email: string;
  givenName: string;
  familyName?: string;
}) {
  const result = await square.customers.create({
    emailAddress: opts.email,
    givenName: opts.givenName,
    familyName: opts.familyName,
    referenceId: 'wrench-web'
  });
  return result.customer;
}

/**
 * Subscribe a waitlist email to Square Marketing (optional — falls back to local DB).
 * TODO: Wire up when Square Marketing API endpoint is confirmed.
 */
export async function addToSquareMarketing(_email: string): Promise<void> {
  // TODO: Implement via Square Marketing API when sandbox is ready
  // For now, waitlist emails are stored only in the local DB
}
